# Generated by Django 4.1.4 on 2022-12-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
