# Generated by Django 4.1.4 on 2022-12-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
