# Generated by Django 4.1.4 on 2022-12-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movies_date_created_alter_movies_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='watched',
        ),
        migrations.AlterField(
            model_name='movies',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(max_length=20, verbose_name='type'),
        ),
    ]
