# Generated by Django 4.1.4 on 2022-12-20 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movies_watched_alter_movies_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movies'},
        ),
        migrations.AddField(
            model_name='movies',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Deleted date'),
        ),
        migrations.AddField(
            model_name='movies',
            name='modify_date',
            field=models.DateField(auto_now=True, verbose_name='Modify date'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ScoreMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Modify date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('score', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Movie Name')),
            ],
            options={
                'verbose_name': 'score',
            },
        ),
    ]
