# Generated by Django 4.1.4 on 2022-12-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movies_options_movies_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='score',
        ),
        migrations.AddField(
            model_name='movies',
            name='mean_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
