# Generated by Django 4.1.4 on 2022-12-20 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movies_score_movies_mean_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Modify date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('View', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Movie Name')),
            ],
            options={
                'verbose_name': 'score',
            },
        ),
    ]
