# Generated by Django 4.1.4 on 2022-12-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_viewmovie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewmovie',
            options={'verbose_name': 'Views'},
        ),
        migrations.RenameField(
            model_name='scoremovie',
            old_name='name',
            new_name='name_id',
        ),
        migrations.RenameField(
            model_name='viewmovie',
            old_name='name',
            new_name='name_id',
        ),
    ]
