# Generated by Django 4.1.4 on 2022-12-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_viewmovie_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewmovie',
            old_name='View',
            new_name='view',
        ),
    ]
