# Generated by Django 4.1.4 on 2022-12-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movies_mean_score_remove_movies_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoremovie',
            old_name='name_id',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='viewmovie',
            old_name='name_id',
            new_name='name',
        ),
    ]
