# Generated by Django 4.1.4 on 2022-12-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_name_id_scoremovie_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeanScoreMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Modify date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('mean_score', models.DecimalField(decimal_places=2, max_digits=2)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Movie Name')),
            ],
            options={
                'verbose_name': 'Views',
            },
        ),
    ]
