# Generated by Django 4.1.4 on 2022-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movies_mean_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
