# Generated by Django 4.1.4 on 2022-12-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_movies_mean_score_remove_movies_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='mean_score',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
